FROM debian:bullseye

#auto update and upgrade
RUN apt-get update && apt-get upgrade -y && \
	    echo "Update and upgrade done" && \

# Installation
# Client is installed so we can have access to mysql command line
	apt-get install -y mariadb-server mariadb-client && \
	rm -rf /var/lib/apt/lists/*

#copying configs from the script and adding execution rights to it
COPY ./conf/mdb_conf.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/mdb_conf.sh

#exposing the MySQL port 3306
EXPOSE 3306

#Configuration must run when container starts
ENTRYPOINT ["/usr/local/bin/mdb_conf.sh"]